


SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Employees] (
    [EmployeeId] INT IDENTITY(1,1) NOT NULL,
    [Name] VARCHAR(250) NOT NULL,
    [Address] VARCHAR(250) NOT NULL,
    [ImagePath] VARCHAR(250) NOT NULL,
    CONSTRAINT [PK_Employees] PRIMARY KEY CLUSTERED (
        [EmployeeId] ASC
    ) WITH (
        PAD_INDEX = OFF, 
        STATISTICS_NORECOMPUTE = OFF, 
        IGNORE_DUP_KEY = OFF, 
        ALLOW_ROW_LOCKS = ON, 
        ALLOW_PAGE_LOCKS = ON
    ) ON [PRIMARY]
) ON [PRIMARY];
GO
